---
- hosts: all

  vars:

    apps:
      - apache-directory-studio
      - arq
      - atom # sublime without annoying popup | https://atom.io/download/mac 
      - charles
      - docker
      - dropbox # a worse Mega Sync
      - electrum
      - evernote
      - expandrive
      - filezilla
      - firefox
      - google-chrome
      - chrome-remote-desktop-host
      - iglasses
      - iterm2 
      - karabiner # Keyboard customization
      - ledger-live
      - lucidchart
      - microsoft-office
      - microsoft-teams
      - mimecast
      - monero-wallet
      - paw
      - pixelmator
      - pingplotter
      - powershell
      - pycharm
      - razer-synapse
      - remote-desktop-connection
      - skitch 
      - sublime-text
      - the-unarchiver
      - utorrent
      - vagrant # | https://www.vagrantup.com/downloads.html
      - vagrant-manager # 
      - virtualbox # | https://www.virtualbox.org/
      - visual-studio-code
      - vmware-fusion
      - webstorm
      - xld
      - zoomus

    mas_installed_apps:
      - { id: 466416967, name: "NavicatPremiumEssentials (11.2.18)" }
      - { id: 926036361, name: "LastPass (4.4.0)" }

    install_oh_my_zsh:  false
    install_mas_apps: false

    dotfiles_repo: "https://github.com/asagage/dotfiles.git"
    dotfiles_repo_version: master
    dotfiles_repo_accept_hostkey: false
    dotfiles_repo_local_destination: "~/.dotfiles"

    brew_utils:
      - docker # | https://docs.docker.com/installation/mac/
      - git
      - grc
      - python
      - tmux
      - vim
      - wget
      - zsh

    zsh_path: /usr/local/bin/zsh

    home: "{{ lookup('env','HOME') }}"

  roles: 
    - { role: geerlingguy.mas }

  tasks:
    
    - name: Check Homebrew is installed
      stat: 
        path: /usr/local/bin/brew
      register: brew_installed

    - name: Install Homebrew
      shell: ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
      when: not brew_installed.stat.exists

    - name: update homebrew
      homebrew:
        update_homebrew: yes
    
    ### UTILS

    - name: Install libraries/utils with homebrew
      homebrew: 
        name: "{{ brew_utils }}" 
        state: present
    
    - name: Cleanup after brewing
      shell: brew cleanup

    ### APPZ

    - name: Install Apps with homebrew_cask
      homebrew_cask:
        name: "{{ apps }}"

    ### ZSH radness 

    - name: Determine if zsh is default/current shell
      shell: echo $SHELL
      register: current_shell

    - name: Enable zsh in /etc/shells
      shell: /bin/sh -c 'grep -q "{{ zsh_path }}" /etc/shells || echo "{{ zsh_path }}" >> /etc/shells'
      become: true
      when: current_shell.stdout != '/usr/local/bin/zsh' 

    - name: Set zsh as default shell
      shell: chsh -s {{ zsh_path }}
      when: current_shell.stdout != '/usr/local/bin/zsh'
      become: true

    - name: Install oh-my-zsh
      git: repo=https://github.com/robbyrussell/oh-my-zsh dest=~/.oh-my-zsh
      when: install_oh_my_zsh == true
      tags: install_oh_my_zsh

    ### OSX SETTINGS

#      - name: Configure System Settings
#      script: scripts/system_settings.sh
#      become: true

    ### DOTFILES
    - name: Ensure dotfiles repository is cloned locally.
      git:
        repo: "{{ dotfiles_repo }}"
        dest: "{{ dotfiles_repo_local_destination }}"
        version: "{{ dotfiles_repo_version }}"
        accept_hostkey: "{{ dotfiles_repo_accept_hostkey }}"
      become: false

    - debug:
        msg: "When you are ready to install the dotfiles, cd into ~/.dotfiles and run 'script/bootstrap'"

    ## POST INSTALL STEPS / Cask gotchas
    #
    # require manual intervention!
    #
