---
- hosts: all

  vars:

    apps:
      - atom # sublime without annoying popup | https://atom.io/download/mac 
      - dropbox # a worse Mega Sync
      - google-chrome
      - iterm2 
      - karabiner # Keyboard customization
      - skitch 
      - vagrant # | https://www.vagrantup.com/downloads.html
      - vagrant-manager # 
      - virtualbox # | https://www.virtualbox.org/

    install_oh_my_zsh:  true

    dotfile_repo_username: asagage # the GH repo where your dotfiles are

    brew_utils:
      - docker # | https://docs.docker.com/installation/mac/
      - git
      - python
      - tmux
      - vim
      - wget
      - zsh

    zsh_path: /usr/local/bin/zsh

    home: "{{ lookup('env','HOME') }}"

  tasks:
    
    - name: Check Homebrew is installed
      stat: 
        path: /usr/local/bin/brew
      register: brew_installed

    - name: Install Homebrew
      shell: ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
      when: not brew_installed.stat.exists

    - name: update homebrew
      homebrew:
      update_homebrew: yes
    
    ### UTILS

    - name: Install libraries/utils with homebrew
      homebrew: 
        name: "{{ brew_utils }}" 
        state: present
    
    - name: Cleanup after brewing
      shell: brew cleanup

    ### APPZ

    - name: Install Apps with homebrew_cask
      homebrew_cask:
        name: "{{ apps }}"

    ### ZSH radness 

    - name: Determine if zsh is default/current shell
      shell: echo $SHELL
      register: current_shell

    - name: Enable zsh in /etc/shells
      shell: sudo /bin/sh -c 'grep -q "{{ zsh_path }}" /etc/shells || echo "{{ zsh_path }}" >> /etc/shells'
      when: current_shell.stdout != '/usr/local/bin/zsh'    

    - name: Set zsh as default shell
      shell: chsh -s {{ zsh_path }}
      when: current_shell.stdout != '/usr/local/bin/zsh'
      sudo: true

    - name: Install oh-my-zsh
      git: repo=https://github.com/robbyrussell/oh-my-zsh dest=~/.oh-my-zsh
      sudo: false
      when: install_oh_my_zsh == true
      tags: install_oh_my_zsh

    ### OSX SETTINGS

    - name: Configure System Settings
      script: scripts/system_settings.sh
      sudo: true

    ### DOTFILES


    ## POST INSTALL STEPS / Cask gotchas
    #
    # require manual intervention!
    #
